oa3_spec: ./openapi/openapi.json
name: opex_pagopa-receipt-service-messages
location: West Europe
timespan: 5m
data_source: /subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-api-rg/providers/Microsoft.ApiManagement/service/pagopa-p-apim
resource_type: api-management
action_groups:
  - /subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/microsoft.insights/actionGroups/PagoPA
  - /subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/microsoft.insights/actionGroups/SlackPagoPA
  - /subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/microsoft.insights/actionGroups/Opsgenie
availability_threshold: 0.90
response_time_threshold: 9.0
overrides:
  hosts:
    - api.platform.pagopa.it
  base_path: "/receipts/service/v1"
  endpoints:
    GET /messages/{tp_id}/{attachment_url}:
      response_time_threshold: 3 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default: 1
    GET /messages/{tp_id}:
      response_time_threshold: 2 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default: 1
