apiVersion: v2
name: pagopareceiptpdfservice
description: Microservice pagopa-receipt-pdf-service
type: application
version: 0.65.0
appVersion: 0.12.1-PAGOPA-3416-receipt-cart-get-attachment-details
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
