apiVersion: v2
name: pagopareceiptpdfservice
description: Microservice pagopa-receipt-pdf-service
type: application
version: 0.67.0
appVersion: 0.13.1
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: pagopa-receipt-pdf-service
